export const state = () => ({
  qiyuList: [
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' },
    { map: "地图名称", start_npc: "xxx", coordinate: 'x: 0, y: 0', name: '奇遇名称' }
  ]
})

export const mutations = {

}
